### ISSUE TITLE
Build stops working on errors during the build process

### ISSUE THREAD

**Issue by OrKoN** [jackfranklin/jspm-dev-builder#11]
To track another problem with errors in plugins/build process.

Steps to reproduce:
1. start a non-sfx build
2. put some bad handlebars to `main.hbs` (e.g. `{{#test}}`) and save
3. a build is attempted and an error is printed to the console (e.g. `Expecting 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF'`)
4. remove the bad handlebars piece and save

Expected: the build is successful again.
Actual: the build fails because of the bad handlebars that is not present in the file anymore

**Comment by jackfranklin** [comment]
:+1: I'll try to find some time to work on this soon, but if anyone else beats me a PR is welcome!

**Comment by OrKoN** [comment]
I think it's more the problem of systemjs-builder than of this project. Have not had time to look into this in more details.

**Comment by Bnaya** [comment]
Should be resolved with the next release of jspm!

**Comment by Bnaya** [comment]
Should be reloved on when updating to the last release of JSPM

**Comment by zakshevsky** [comment]
Tested with 0.16.20 JSPM - works for me.

**Comment by jackfranklin** [comment]
Perfect! I'll try to release a new jspm-dev-builder that comes with 0.16.20 by default soon.

**Comment by Bnaya** [comment]
Maybe set jspm as peer dependency ?

**Comment by jackfranklin** [comment]
0.4.0 has the latest jspm version.
