### ISSUE TITLE
Every other build w/ Babel breaks

### ISSUE THREAD

**Issue by tjclement** [jackfranklin/jspm-dev-builder#16]
When using jspm-dev-builder to enable partial rebuilds of an app, having configured jspm to transpile with Babel, every other built bundle seems to contain non-canonicalized dependencies in the file that was changed. Performing another partial build, again first invalidating that same file, corrects the issue, but the bundle after that breaks it again etc. 

This is what the bundle looks like, correct on the left and broken on the right:
![](http://i.imgur.com/6m6mfkZ.png)

A repro test can be found here https://gist.github.com/tjclement/7d6e606b2ba4411ced51

This is caused by a bug in systemjs/builder, which is tracked at https://github.com/systemjs/builder/issues/448

**Comment by jackfranklin** [comment]
I think this should be fixed now given that issue is sorted?

**Comment by tjclement** [comment]
Yep!
