### ISSUE TITLE
Source maps support?

### ISSUE THREAD

**Issue by OrKoN** [jackfranklin/jspm-dev-builder#2]
The project is great! But I wonder if you use it w/o source map support? Is it possible to have source maps for the bundle?

**Comment by jackfranklin** [comment]
Yeah, this would just need to be an option that's added. I'll add it :+1:

**Comment by jackfranklin** [comment]
@OrKoN I think https://github.com/jackfranklin/jspm-dev-builder/commit/f9293dc0cacbaa0069d6f9016a0f6d31666c5b59 should solve this :)

I'll hopefully publish 0.2 with it in later today

**Comment by OrKoN** [comment]
Thanks @jackfranklin sounds great!
