### ISSUE TITLE
Use new builder invalidation API

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/jspm-dev-builder#3]
pending https://github.com/systemjs/builder/pull/341

**Comment by OrKoN** [comment]
Looks like this is released now?

**Comment by jackfranklin** [comment]
@OrKoN yup, there's #4 open and soon to be merged

**Comment by jackfranklin** [comment]
#4 is now out in 0.2

**Comment by OrKoN** [comment]
@jackfranklin It looks like with the new API the re-builds are broken because I see the entire app is being rebuilt on any change.

**Comment by jackfranklin** [comment]
@OrKoN not seeing that behaviour myself - I do test things before releasing ;) You need to make sure you're using jspm 0.16.12 or newer. Open a new issue if you can't get it figured.

**Comment by OrKoN** [comment]
@jackfranklin I am not saying you don't test :-) I have extended your test to include loader plugins: https://github.com/OrKoN/jspm-dev-builder/tree/master/test-project Whenever I change main.js, main.hbs gets re-compiled too. I suspect that the new invalidation API invalidates more stuff than your implementation did previously.

**Comment by jackfranklin** [comment]
@OrKoN interesting. `this.builder.invalidate()` should return an array of the things it invalidated, I think, so a sensible place to start would be to see what that's returning. Sounds like maybe it's being a little over-eager. I'll try to take a look later if I have time. @guybedford would be interesting to get your thoughts.
