### ISSUE TITLE
builder.build is deprecated. Using builder.bundle instead.

### ISSUE THREAD

**Issue by seangwright** [jackfranklin/jspm-dev-builder#6]
When I use my version of jspm (0.16.13) I get this warning because the API is changing in the systemjs builder. SFX has also been renamed to Static. (see https://github.com/systemjs/builder/releases/tag/0.14.0)

This repo depends on jspm `"^0.16.12"` so shouldn't this usage of jspm's internal version of the systemjs-builder be updated to reflected the updated API?

**Comment by jackfranklin** [comment]
Yes, it should. I just missed it the last time I did a release. I'll try to fix it up at some point, but in the mean time it's just a deprecation warning so I'm in no huge rush.

**Comment by OrKoN** [comment]
included in this PR https://github.com/jackfranklin/jspm-dev-builder/pull/8

**Comment by jackfranklin** [comment]
Fixed in 0.3.1 thanks to @OrKoN
