### ISSUE TITLE
Doesn't change subsequent output?

### ISSUE THREAD

**Issue by iksose** [jackfranklin/jspm-dev-builder#7]
When called from the gulp task the first time, all changes are reflected. However, once `chokidar` emits a file changed and I pass it to `appDevBuilder`, it says it's invalidating it from cache and I get a "jspm build finished xxx" but the output isn't actually changed when I inspect the file.

I'm using almost the same config verbatim, except my input & output is nested a few folders deep -- but like I said, `chokidar` finds and passes the changed file file. Is there some special consideration I'm missing, because I thought it would be as simple as passing the path to the instantiated jspm-dev-builder object

jspm 0.16.12

**Comment by jackfranklin** [comment]
Interesting - it should work with just a regular filename. Is this code online anywhere?

I've not had a chance to look in depth but this may be related to https://github.com/systemjs/builder/issues/353

**Comment by iksose** [comment]
I'm passing it the full path, should I be passing just the filename?

**Comment by jackfranklin** [comment]
Quite possibly :+1:

**Comment by iksose** [comment]
Probably related to the issue linked, when I pass the full path (after upgrading to 0.16.13), the file is deleted from the bundle.

**Comment by jackfranklin** [comment]
What's the behaviour if you just pass the filename?

**Comment by iksose** [comment]
No change if just the file name

**Comment by seangwright** [comment]
This is definitely related to https://github.com/systemjs/builder/issues/353 as @iksose's results are the same thing I'm seeing. If I pass in the same path that systemjs has a reference to in the bundle, then the file is deleted, if I pass just the filename, nothing happens.

I believe this is because the file is not registered with the cache as just the filename. I think it is registered with the whole path. The problem seems to be with the cache invalidation api.

**Comment by guybedford** [comment]
I'd suggest writing `var invalidated = builder.invalidate(...` at https://github.com/jackfranklin/jspm-dev-builder/blob/master/index.js#L23 and log that invalidated array. If the array returns empty that means there wasn't a match for any invalidations. Invalidation names can be any unnormalized module name, but must be in module name space, not file name space (baseURL relative in other words).

**Comment by iksose** [comment]
The output for that is `[ 'file:///path/to/file/here/controller.js' ]`, and then it gets deleted from the bundle.

**Comment by guybedford** [comment]
Thanks, there was a bug here which has been resolved in https://github.com/systemjs/builder/issues/353.

**Comment by iksose** [comment]
Now I get an ENOENT for `my/directory/24.js`, I have no idea what `24.js` is so i'm not surprised it can't find it.

If I pass it an incorrect filepath the error goes away :(

**Comment by iksose** [comment]
Okay, so it seems (with guybedford's patch) that the aforementioned only happens after the first successful validation of the same file. Run it once, builds app. Change a comment, it correctly invalidates and my code is updated, change the -same- file again and it throws.

Basically if I try to consecutively change the same file.

If I switch back and forth between invalidating different files it works.

**Comment by jackfranklin** [comment]
@iksose did you get any further with that? That's really odd :/

Once systemjs-builder's latest fixes by @guybedford are into a jspm release I'll update jspm-dev-builder which should help resolve some of the problems :+1:

**Comment by iksose** [comment]
Apparently it's not supported for sfx builds at this current time.

Also, it's weird that the example in this repo doesn't use the cache-invalidated bundle.js?

**Comment by OrKoN** [comment]
I have submitted a PR https://github.com/jackfranklin/jspm-dev-builder/pull/8 looks like SFX builds work as well. At least according to my tests.

**Comment by jackfranklin** [comment]
@iksose I think 0.3.1 will fix this, all credit to @OrKoN. If it doesn't please let me know.
